// Generated by FIX2AdHoc (SBE message schema) (https://github.com/AdHoc-Protocol)
// Sources: basic-types-schema.xml
// SBE package: SBE tests, schema id: 3, version: , semanticVersion: 5.2, byteOrder: littleEndian
// Schema description: Unit Test
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.fix {
    /**
        <see cref = 'Message1'/>
        <see cref = 'Message1WithOffsets'/>
    */
    public interface basic_types_schema {

        // Permissive defaults for FIX-sourced data — override per field with [D(+N)] / [D(N)].
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ messages ═════════════════════════

        class Message1 {
            public const int template_id = 1; // SBE message id
            [Tag(41)] messageHeader header;
            [Tag(42)] EDT EDTField;
            [Tag(43)] ENUM ENUMField;
            [Tag(44)] SET SETField;
            [Tag(45), SemanticType("int")] long int64Field;
        }

        class Message1WithOffsets {
            public const int template_id = 2; // SBE message id
            [Tag(41)] messageHeader header;
            [Tag(42)] EDT EDTField;
            [Tag(43)] ENUM ENUMField;
            [Tag(44)] SET SETField;
            [Tag(45), SemanticType("int")] long int64Field;
        }

        // ═════════════════════════ types (typedefs, enums, sets, composites) ═════════════════════════

        /**
        Message identifiers and length of message root
        */
        class messageHeader {
            ushort blockLength;
            ushort templateId;
            ushort schemaId;
            ushort version;
        }

        /**
        char array
        */
        class EDT { [D(+20), SemanticType("char")] string TYPEDEF; }

        /**
        enum as uint8
        */
        enum ENUM {
            Value1 = 1,
            Value10 = 10,
        }

        /**
        set as uint32
        */
        [Flags]
        enum SET {
            Bit0 = 1,
            Bit16 = 65536,
            Bit26 = 67108864,
        }

        // ═════════════════════════ topology ═════════════════════════

        // The side that opens the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Initiator : Host { }

        // The side that accepts the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Acceptor : Host { }

        interface Session : Connects<Initiator, Acceptor> {
            // Every SBE message, either direction; composites and typedefs stay sub-packs.
            [_____lr_____<(Message1, Message1WithOffsets)>]
            struct Established { }
        }

        // ═════════════════════════ SBE metadata attributes ═════════════════════════

        /** SBE field id (the FIX tag number). */
        public class TagAttribute : Attribute { public TagAttribute(int id) { } }

        /** Schema version that introduced the element. */
        public class SinceVersionAttribute : Attribute { public SinceVersionAttribute(int version) { } }

        /** Schema version that deprecated the element. */
        public class DeprecatedAttribute : Attribute { public DeprecatedAttribute(int version) { } }

        /** Wire value that means 'not set' for an optional encoding. */
        public class NullValueAttribute : Attribute { public NullValueAttribute(string value) { } }

        /** Character encoding of a char / var-data encoding. */
        public class CharacterEncodingAttribute : Attribute { public CharacterEncodingAttribute(string encoding) { } }

        /** FIX semantic data type of the encoding (Qty, Price, UTCTimestamp, ...). */
        public class SemanticTypeAttribute : Attribute { public SemanticTypeAttribute(string type) { } }

        /** Composite that frames the repeating group on the wire. */
        public class DimensionTypeAttribute : Attribute { public DimensionTypeAttribute(string composite) { } }

        /** Fixed block length of the message / group root block on the SBE wire. */
        public class BlockLengthAttribute : Attribute { public BlockLengthAttribute(long bytes) { } }

    }
}
