// Generated by FIX2AdHoc (SBE message schema) (https://github.com/AdHoc-Protocol)
// Sources: car.xml
// SBE package: uk.co.real_logic.sbe.benchmarks, schema id: 1, version: 1, semanticVersion: 5.2, byteOrder: littleEndian
// Schema description: Example schema
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.fix {
    /**
        <see cref = 'Car'/>
    */
    public interface car {

        // Permissive defaults for FIX-sourced data — override per field with [D(+N)] / [D(N)].
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ messages ═════════════════════════

        /**
        Description of a basic Car
        */
        class Car {
            public const int template_id = 1; // SBE message id
            [Tag(1)] uint serialNumber;
            [Tag(2)] ushort modelYear;
            [Tag(3)] BooleanType available;
            [Tag(4)] Model code;
            [Tag(5)] someNumbers someNumbers;
            [Tag(6)] VehicleCode vehicleCode;
            [Tag(7)] OptionalExtras extras;
            [Tag(8)] Engine engine;
            [Tag(9), DimensionType("groupSizeEncoding"), D(65535)] FuelFiguresGroup[,,] fuelFigures;
            public class FuelFiguresGroup {
                [Tag(10)] ushort speed;
                [Tag(11)] float mpg;
            }
            [Tag(12), DimensionType("groupSizeEncoding"), D(65535)] PerformanceFiguresGroup[,,] performanceFigures;
            public class PerformanceFiguresGroup {
                [Tag(13)] byte octaneRating;
                [Tag(14), DimensionType("groupSizeEncoding"), D(65535)] AccelerationGroup[,,] acceleration;
                public class AccelerationGroup {
                    [Tag(15)] ushort mph;
                    [Tag(16)] float seconds;
                }
            }
            [Tag(17), D(+1048576), CharacterEncoding("ISO-8859-1"), DeclaredMaxLength(1073741824)] string manufacturer;
            [Tag(18), D(+1048576), CharacterEncoding("ISO-8859-1"), DeclaredMaxLength(1073741824)] string model;
        }

        // ═════════════════════════ types (typedefs, enums, sets, composites) ═════════════════════════

        /**
        Message identifiers and length of message root
        */
        class messageHeader {
            ushort blockLength;
            ushort templateId;
            ushort schemaId;
            ushort version;
        }

        /**
        Repeating group dimensions
        */
        class groupSizeEncoding {
            ushort blockLength;
            ushort numInGroup;
        }

        class varStringEncoding {
            uint length;
            [D(65535), CharacterEncoding("ISO-8859-1")] Binary[,,] varData;
        }

        class varDataEncoding {
            uint length;
            [D(65535)] Binary[,,] varData;
        }

        class VehicleCode { [D(+6)] string TYPEDEF; }

        class someNumbers { [D(5)] int[] TYPEDEF; }

        class Engine {
            ushort capacity;
            byte numCylinders;
            const ushort maxRpm = 9000;
            [D(+3)] string manufacturerCode;
            const string fuel = "Petrol";
        }

        enum BooleanType {
            F = 0,
            T = 1,
        }

        enum Model {
            A = 'A',
            B = 'B',
            C = 'C',
        }

        [Flags]
        enum OptionalExtras {
            sunRoof = 1,
            sportsPack = 2,
            cruiseControl = 4,
        }

        // ═════════════════════════ topology ═════════════════════════

        // The side that opens the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Initiator : Host { }

        // The side that accepts the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Acceptor : Host { }

        interface Session : Connects<Initiator, Acceptor> {
            // Every SBE message, either direction; composites and typedefs stay sub-packs.
            [_____lr_____<Car>]
            struct Established { }
        }

        // ═════════════════════════ SBE metadata attributes ═════════════════════════

        /** SBE field id (the FIX tag number). */
        public class TagAttribute : Attribute { public TagAttribute(int id) { } }

        /** Schema version that introduced the element. */
        public class SinceVersionAttribute : Attribute { public SinceVersionAttribute(int version) { } }

        /** Schema version that deprecated the element. */
        public class DeprecatedAttribute : Attribute { public DeprecatedAttribute(int version) { } }

        /** Wire value that means 'not set' for an optional encoding. */
        public class NullValueAttribute : Attribute { public NullValueAttribute(string value) { } }

        /** Character encoding of a char / var-data encoding. */
        public class CharacterEncodingAttribute : Attribute { public CharacterEncodingAttribute(string encoding) { } }

        /** FIX semantic data type of the encoding (Qty, Price, UTCTimestamp, ...). */
        public class SemanticTypeAttribute : Attribute { public SemanticTypeAttribute(string type) { } }

        /** Composite that frames the repeating group on the wire. */
        public class DimensionTypeAttribute : Attribute { public DimensionTypeAttribute(string composite) { } }

        /** Fixed block length of the message / group root block on the SBE wire. */
        public class BlockLengthAttribute : Attribute { public BlockLengthAttribute(long bytes) { } }

        /** The schema allows this many items; the AdHoc cap was reduced to 1048576. */
        public class DeclaredMaxLengthAttribute : Attribute { public DeclaredMaxLengthAttribute(long items) { } }

    }
}
