// Generated by FIX2AdHoc (SBE message schema) (https://github.com/AdHoc-Protocol)
// Sources: example-schema.xml, common-types.xml
// SBE package: baseline, schema id: 1, version: 0, semanticVersion: 5.2, byteOrder: littleEndian
// Schema description: Example base schema which can be extended.
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.fix {
    /**
        <see cref = 'Car'/>
    */
    public interface example_schema {

        // Permissive defaults for FIX-sourced data — override per field with [D(+N)] / [D(N)].
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ messages ═════════════════════════

        /**
        Description of a basic Car
        */
        class Car {
            public const int template_id = 1; // SBE message id
            [Tag(1)] ulong serialNumber;
            [Tag(2)] ushort modelYear;
            [Tag(3)] BooleanType available;
            [Tag(4)] Model code;
            [Tag(5)] someNumbers someNumbers;
            [Tag(6)] VehicleCode vehicleCode;
            [Tag(7)] OptionalExtras extras;
            const char discountedModel = 'C'; // Model.C
            [Tag(9)] Engine engine;
            [Tag(10), DimensionType("groupSizeEncoding"), D(65535)] FuelFiguresGroup[,,] fuelFigures;
            public class FuelFiguresGroup {
                [Tag(11)] ushort speed;
                [Tag(12)] float mpg;
                [Tag(200), D(+1048576), CharacterEncoding("ASCII"), DeclaredMaxLength(1073741824)] string usageDescription;
            }
            [Tag(13), DimensionType("groupSizeEncoding"), D(65535)] PerformanceFiguresGroup[,,] performanceFigures;
            public class PerformanceFiguresGroup {
                [Tag(14)] Ron octaneRating;
                [Tag(15), DimensionType("groupSizeEncoding"), D(65535)] AccelerationGroup[,,] acceleration;
                public class AccelerationGroup {
                    [Tag(16)] ushort mph;
                    [Tag(17)] float seconds;
                }
            }
            [Tag(18), D(+1048576), CharacterEncoding("UTF-8"), DeclaredMaxLength(1073741824)] string manufacturer;
            [Tag(19), D(+1048576), CharacterEncoding("UTF-8"), DeclaredMaxLength(1073741824)] string model;
            [Tag(20), D(+1048576), CharacterEncoding("ASCII"), DeclaredMaxLength(1073741824)] string activationCode;
        }

        // ═════════════════════════ types (typedefs, enums, sets, composites) ═════════════════════════

        /**
        Message identifiers and length of message root.
        */
        class messageHeader {
            ushort blockLength;
            ushort templateId;
            ushort schemaId;
            ushort version;
        }

        /**
        Repeating group dimensions.
        */
        class groupSizeEncoding {
            ushort blockLength;
            ushort numInGroup;
        }

        /**
        Variable length UTF-8 String.
        */
        class varStringEncoding {
            uint length;
            [D(65535), CharacterEncoding("UTF-8")] Binary[,,] varData;
        }

        /**
        Variable length ASCII String.
        */
        class varAsciiEncoding {
            uint length;
            [D(65535), CharacterEncoding("ASCII")] Binary[,,] varData;
        }

        /**
        Variable length binary blob.
        */
        class varDataEncoding {
            uint length;
            [D(65535)] Binary[,,] varData;
        }

        class VehicleCode { [D(+6), CharacterEncoding("ASCII")] string TYPEDEF; }

        class Ron { [MinMax(90, 110)] byte TYPEDEF; }

        class someNumbers { [D(4)] uint[] TYPEDEF; }

        class Percentage { [MinMax(0, 100)] sbyte TYPEDEF; }

        enum BoostType {
            TURBO = 'T',
            SUPERCHARGER = 'S',
            NITROUS = 'N',
            KERS = 'K',
        }

        class Booster {
            BoostType BoostType;
            byte horsePower;
        }

        /**
        Boolean Type.
        */
        enum BooleanType {
            /**
            False value representation.
            */
            F = 0,
            /**
            True value representation.
            */
            T = 1,
        }

        class Engine {
            ushort capacity;
            byte numCylinders;
            const ushort maxRpm = 9000;
            [D(+3)] string manufacturerCode;
            const string fuel = "Petrol";
            Percentage efficiency;
            BooleanType boosterEnabled;
            Booster booster;
        }

        enum Model {
            A = 'A',
            B = 'B',
            C = 'C',
        }

        [Flags]
        enum OptionalExtras {
            sunRoof = 1,
            sportsPack = 2,
            cruiseControl = 4,
        }

        // ═════════════════════════ topology ═════════════════════════

        // The side that opens the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Initiator : Host { }

        // The side that accepts the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Acceptor : Host { }

        interface Session : Connects<Initiator, Acceptor> {
            // Every SBE message, either direction; composites and typedefs stay sub-packs.
            [_____lr_____<Car>]
            struct Established { }
        }

        // ═════════════════════════ SBE metadata attributes ═════════════════════════

        /** SBE field id (the FIX tag number). */
        public class TagAttribute : Attribute { public TagAttribute(int id) { } }

        /** Schema version that introduced the element. */
        public class SinceVersionAttribute : Attribute { public SinceVersionAttribute(int version) { } }

        /** Schema version that deprecated the element. */
        public class DeprecatedAttribute : Attribute { public DeprecatedAttribute(int version) { } }

        /** Wire value that means 'not set' for an optional encoding. */
        public class NullValueAttribute : Attribute { public NullValueAttribute(string value) { } }

        /** Character encoding of a char / var-data encoding. */
        public class CharacterEncodingAttribute : Attribute { public CharacterEncodingAttribute(string encoding) { } }

        /** FIX semantic data type of the encoding (Qty, Price, UTCTimestamp, ...). */
        public class SemanticTypeAttribute : Attribute { public SemanticTypeAttribute(string type) { } }

        /** Composite that frames the repeating group on the wire. */
        public class DimensionTypeAttribute : Attribute { public DimensionTypeAttribute(string composite) { } }

        /** Fixed block length of the message / group root block on the SBE wire. */
        public class BlockLengthAttribute : Attribute { public BlockLengthAttribute(long bytes) { } }

        /** The schema allows this many items; the AdHoc cap was reduced to 1048576. */
        public class DeclaredMaxLengthAttribute : Attribute { public DeclaredMaxLengthAttribute(long items) { } }

    }
}
