// Generated by FIX2AdHoc (SBE message schema) (https://github.com/AdHoc-Protocol)
// Sources: fix-message-samples.xml
// SBE package: uk.co.real_logic.sbe.benchmarks.fix, schema id: 1, version: 1, semanticVersion: 5.2, byteOrder: littleEndian
// Schema description: Order Types and Quote Examples
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.fix {
    /**
        <see cref = 'MarketDataIncrementalRefresh'/>
        <see cref = 'MarketDataIncrementalRefreshTrades'/>
        <see cref = 'MassQuote'/>
        <see cref = 'NewOrder'/>
        <see cref = 'OrderCancelReplaceRequest'/>
        <see cref = 'OrderCancelRequest'/>
    */
    public interface fix_message_samples {

        // Permissive defaults for FIX-sourced data — override per field with [D(+N)] / [D(N)].
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ messages ═════════════════════════

        /**
        submit a new order on an instrument
        */
        class NewOrder {
            public const int template_id = 68; // SBE message id
            public const string SEMANTIC_TYPE = "D"; // FIX MsgType
            [Tag(1), SemanticType("String")] string12 Account;
            [Tag(11), SemanticType("String")] string20 ClOrdID;
            [Tag(21), SemanticType("char")] char HandInst; // values: HandInst
            [Tag(1031), SemanticType("char")] CustOrderHandlingInst? CustOrderHandlingInst;
            [Tag(38), SemanticType("Qty")] IntQty32 OrderQty;
            [Tag(40), SemanticType("char")] OrdType OrdType;
            [Tag(44), SemanticType("Price")] OptionalPrice Price;
            [Tag(54), SemanticType("char")] Side Side;
            [Tag(55), SemanticType("String")] Symbol Symbol;
            [Tag(59), SemanticType("char")] TimeInForce? TimeInForce;
            [Tag(60), SemanticType("UTCTimestamp")] ulong TransactTime;
            [Tag(1028)] BooleanType ManualOrderIndicator;
            [Tag(79), SemanticType("String")] string10 AllocAccount;
            [Tag(99), SemanticType("Price")] OptionalPrice StopPx;
            [Tag(107), SemanticType("String")] string20 SecurityDesc;
            [Tag(110), SemanticType("Qty")] IntQty32 MinQty;
            [Tag(167), SemanticType("String")] string3 SecurityType;
            [Tag(204)] CustomerOrFirm CustomerOrFirm;
            [Tag(210), SemanticType("Qty")] IntQty32 MaxShow;
            [Tag(432), SemanticType("LocalMktDate")] ushort ExpireDate;
            [Tag(7928), SemanticType("String")] string12 SelfMatchPreventionID;
            [Tag(9702)] CtiCode CtiCode;
            [Tag(9707), SemanticType("String")] string3 GiveUpFirm;
            [Tag(9708), SemanticType("String")] string2 CmtaGiveupCD;
            [Tag(9717), SemanticType("String")] string20 CorrelationClOrdID;
        }

        class OrderCancelRequest {
            public const int template_id = 70; // SBE message id
            public const string SEMANTIC_TYPE = "F"; // FIX MsgType
            [Tag(1), SemanticType("String")] string12 Account;
            [Tag(11), SemanticType("String")] string20 ClOrdID;
            [Tag(37), SemanticType("int")] long OrderID;
            [Tag(41), SemanticType("String")] string20 OrigClOrdID;
            [Tag(54), SemanticType("char")] Side Side;
            [Tag(55), SemanticType("String")] Symbol Symbol;
            [Tag(60), SemanticType("UTCTimestamp")] ulong TransactTime;
            [Tag(1028)] BooleanType ManualOrderIndicator;
            [Tag(107), SemanticType("String")] string20 SecurityDesc;
            [Tag(167), SemanticType("String")] string3 SecurityType;
            [Tag(9717), SemanticType("String")] string20 CorrelationClOrdID;
        }

        class OrderCancelReplaceRequest {
            public const int template_id = 71; // SBE message id
            public const string SEMANTIC_TYPE = "G"; // FIX MsgType
            [Tag(1), SemanticType("String")] string12 Account;
            [Tag(11), SemanticType("String")] string20 ClOrdID;
            [Tag(37), SemanticType("int")] long OrderID;
            [Tag(21), SemanticType("char")] char HandInst; // values: HandInst
            [Tag(38), SemanticType("Qty")] IntQty32 OrderQty;
            [Tag(1031), SemanticType("char")] CustOrderHandlingInst? CustOrderHandlingInst;
            [Tag(40), SemanticType("char")] OrdType OrdType;
            [Tag(41), SemanticType("String")] string20 OrigClOrdID;
            [Tag(44), SemanticType("Price")] OptionalPrice Price;
            [Tag(54), SemanticType("char")] Side Side;
            [Tag(55), SemanticType("String")] Symbol Symbol;
            [Tag(58), SemanticType("String")] string18 Test;
            [Tag(59), SemanticType("char")] TimeInForce? TimeInForce;
            [Tag(1028)] BooleanType ManualOrderIndicator;
            [Tag(60), SemanticType("UTCTimestamp")] ulong TransactTime;
            [Tag(78)] char? NoAllocs; // values: NoAllocs
            [Tag(79), SemanticType("String")] string10 AllocAccount;
            [Tag(99), SemanticType("Price")] OptionalPrice StopPx;
            [Tag(107), SemanticType("String")] string20 SecurityDesc;
            [Tag(110), SemanticType("Qty")] IntQty32 MinQty;
            [Tag(167), SemanticType("String")] string3 SecurityType;
            [Tag(204)] CustomerOrFirm CustomerOrFirm;
            [Tag(210), SemanticType("Qty")] IntQty32 MaxShow;
            [Tag(432), SemanticType("LocalMktDate")] ushort ExpireDate;
            [Tag(7928), SemanticType("String")] string12 SelfMatchPreventionID;
            [Tag(9702)] CtiCode CtiCode;
            [Tag(9707), SemanticType("String")] string3 GiveUpFirm;
            [Tag(9708), SemanticType("String")] string2 CmtaGiveupCD;
            [Tag(9717), SemanticType("String")] string20 CorrelationClOrdID;
            [Tag(9768)] OFMOverride OFMOverride;
        }

        class MarketDataIncrementalRefresh {
            public const int template_id = 88; // SBE message id
            public const string SEMANTIC_TYPE = "X"; // FIX MsgType
            [Tag(75), SemanticType("LocalMktDate")] ushort TradeDate;
            [Tag(268), D(65535)] EntriesGroup[,,] Entries;
            public class EntriesGroup {
                [Tag(279)] MDUpdateAction MdUpdateAction;
                [Tag(1023), SemanticType("MDPriceLevel")] byte MdPriceLevel;
                [Tag(269)] MDEntryType MdEntryType;
                [Tag(22), SemanticType("SecurityID")] char SecurityIdSource;
                [Tag(48), SemanticType("InstrumentID")] ulong SecurityId;
                [Tag(83), SemanticType("SequenceNumber")] byte RptSeq;
                [Tag(276)] QuoteCondition QuoteCondition;
                [Tag(270), SemanticType("Price")] Decimal64 MdEntryPx;
                // physics: a count — floored at 0 and unbounded above → consider [A]
                [Tag(346), SemanticType("NumberOfOrders")] uint NumberOfOrders;
                [Tag(273), SemanticType("UTCTimestamp")] ulong MdEntryTime;
                [Tag(271)] IntQty32 MdEntrySize;
                [Tag(336)] MarketStateIdentifier TradingSessionId;
                [Tag(451)] Decimal64 NetChgPrevDay;
                [Tag(274)] TickDirection TickDirection;
                [Tag(286)] OpenCloseSettleFlag OpenCloseSettleFlag;
                [Tag(64), SemanticType("UTCTimestamp")] ulong SettleDate;
                [Tag(277)] TradeCondition TradeCondition;
                [Tag(1020)] IntQty32 TradeVolume;
                [Tag(1070)] byte MdQuoteType; // values: MDQuoteType
                [Tag(5790), SemanticType("UTCTimestamp")] ulong FixingBracket;
                [Tag(5797)] Side AggressorSide;
                [Tag(5799)] MatchEventIndicator MatchEventIndicator;
                [Tag(1003), SemanticType("ExecID")] ulong TradeId;
            }
        }

        /**
        Trade
        */
        class MarketDataIncrementalRefreshTrades {
            public const int template_id = 2; // SBE message id
            public const string SEMANTIC_TYPE = "X"; // FIX MsgType
            [Tag(60), SemanticType("UTCTimestamp")] ulong TransactTime;
            [Tag(37704)] ushort EventTimeDelta;
            [Tag(5799)] MatchEventIndicator MatchEventIndicator;
            [Tag(268), D(65535)] MdIncGrpGroup[,,] MdIncGrp;
            public class MdIncGrpGroup {
                [Tag(1003)] ulong TradeId;
                [Tag(48)] ulong SecurityId;
                [Tag(270)] Decimal64 MdEntryPx;
                [Tag(271)] IntQty32 MdEntrySize;
                // physics: a count — floored at 0 and unbounded above → consider [A]
                [Tag(346)] ushort NumberOfOrders;
                [Tag(279)] MDUpdateAction MdUpdateAction;
                [Tag(83)] byte RptSeq;
                [Tag(5797)] Side AggressorSide;
                const char MdEntryType = '2'; // MDEntryType.TRADE
            }
        }

        class MassQuote {
            public const int template_id = 105; // SBE message id
            public const string SEMANTIC_TYPE = "i"; // FIX MsgType
            [Tag(131), SemanticType("String")] string23 QuoteReqID;
            [Tag(117), SemanticType("String")] string10 QuoteID;
            [Tag(9771), SemanticType("String")] string12 MMAccount;
            [Tag(1028)] BooleanType ManualOrderIndicator;
            [Tag(1031), SemanticType("char")] CustOrderHandlingInst? CustOrderHandlingInst;
            [Tag(204)] CustomerOrFirm CustomerOrFirm;
            [Tag(7928), SemanticType("String")] string12 SelfMatchPreventionID;
            [Tag(9702)] CtiCode CtiCode;
            [Tag(9773)] MMProtectionReset? MMProtectionReset;
            [Tag(296), D(65535)] QuoteSetsGroup[,,] QuoteSets;
            public class QuoteSetsGroup {
                [Tag(302), SemanticType("String")] string3 QuoteSetID;
                [Tag(307), SemanticType("String")] string20 UnderlyingSecurityDesc;
                [Tag(304), SemanticType("int")] byte TotQuoteEntries;
                [Tag(295), D(65535)] QuoteEntriesGroup[,,] QuoteEntries;
                public class QuoteEntriesGroup {
                    [Tag(299), SemanticType("String")] string10 QuoteEntryID;
                    [Tag(55), SemanticType("String")] Symbol Symbol;
                    [Tag(107), SemanticType("String")] string20 SecurityDesc;
                    [Tag(167), SemanticType("String")] string3 SecurityType;
                    [Tag(48), SemanticType("int")] optionalInt64? SecurityID;
                    [Tag(22)] char? SecurityIDSource; // values: SecurityIDSource
                    [Tag(60), SemanticType("UTCTimestamp")] ulong TransactTime;
                    [Tag(132), SemanticType("Price")] OptionalPrice BidPx;
                    // physics: a quantity — non-negative and clustered low → consider [A]
                    [Tag(134), SemanticType("int")] optionalInt64? BidSize;
                    [Tag(133), SemanticType("Price")] OptionalPrice OfferPx;
                    // physics: a quantity — non-negative and clustered low → consider [A]
                    [Tag(135), SemanticType("int")] optionalInt64? OfferSize;
                }
            }
        }

        // ═════════════════════════ types (typedefs, enums, sets, composites) ═════════════════════════

        class string2 { [D(+2), CharacterEncoding("US-ASCII")] string TYPEDEF; }

        class string3 { [D(+3), CharacterEncoding("US-ASCII")] string TYPEDEF; }

        class string10 { [D(+10), CharacterEncoding("US-ASCII")] string TYPEDEF; }

        class string12 { [D(+12), CharacterEncoding("US-ASCII")] string TYPEDEF; }

        class string18 { [D(+18), CharacterEncoding("US-ASCII")] string TYPEDEF; }

        class string20 { [D(+20), CharacterEncoding("US-ASCII")] string TYPEDEF; }

        class string23 { [D(+23), CharacterEncoding("US-ASCII")] string TYPEDEF; }

        class Symbol { [D(+6), CharacterEncoding("US-ASCII")] string TYPEDEF; }

        class optionalInt64 { [SemanticType("int")] long? TYPEDEF; }

        /**
        Message identifiers and length of message root
        */
        class messageHeader {
            ushort blockLength;
            ushort templateId;
            ushort schemaId;
            ushort version;
        }

        [SemanticType("Qty")] class IntQty32 {
            int mantissa;
            const int exponent = 0;
        }

        class Decimal64 {
            long mantissa;
            const int exponent = 7;
        }

        class OptionalPrice {
            long mantissa;
            sbyte exponent;
        }

        [SemanticType("NumInGroup")] class groupSizeEncoding {
            ushort blockLength;
            ushort numInGroup;
        }

        // SBE enum with fewer than two values: AdHoc rejects such enums, kept as a constants container.
        public struct HandInst {
            public const char AUTOMATED_EXECUTION = '1';
        }

        enum CustOrderHandlingInst {
            PHONE_SIMPLE = 'A',
            PHONE_COMPLEX = 'B',
            FCM_PROVIDED_SCREEN = 'C',
            OTHER_PROVIDED_SCREEN = 'D',
            CLIENT_PROVIDED_PLATFORM_CONTROLLED_BY_FCM = 'E',
            CLIENT_PROVIDED_PLATFORM_DIRECT_TO_EXCHANGE = 'F',
            FCM_API_OR_FIX = 'G',
            ALGO_ENGINE = 'H',
            PRICE_AT_EXECUTION = 'J',
            DESK_ELECTRONIC = 'W',
            DESK_PIT = 'X',
            CLIENT_ELECTRONIC = 'Y',
            CLIENT_PIT = 'Z',
        }

        enum OrdType {
            MARKET_ORDER = '1',
            LIMIT_ORDER = '2',
            STOP_ORDER = '3',
            STOP_LIMIT_ORDER = '4',
            MARKET_LIMIT_ORDER = 'K',
        }

        enum Side {
            BUY = '1',
            SELL = '2',
        }

        enum TimeInForce {
            DAY = '0',
            GOOD_TILL_CANCEL = '1',
            FILL_AND_KILL = '3',
            GOOD_TILL_DATE = '6',
        }

        enum BooleanType {
            FIX_FALSE = 0,
            FIX_TRUE = 1,
        }

        enum CustomerOrFirm {
            CUSTOMER = 0,
            FIRM = 1,
        }

        enum CtiCode {
            OWN = '1',
            HOUSE = '2',
            ON_FLOOR = '3',
            NOT_ON_FLOOR = '4',
        }

        // SBE enum with fewer than two values: AdHoc rejects such enums, kept as a constants container.
        public struct NoAllocs {
            public const char ONE = '1';
        }

        enum OFMOverride {
            ENABLED = 'Y',
            DISABLED = 'N',
        }

        enum MMProtectionReset {
            RESET = 'Y',
            DO_NOT_RESET = 'N',
        }

        // SBE enum with fewer than two values: AdHoc rejects such enums, kept as a constants container.
        public struct SecurityIDSource {
            public const char EXCHANGE_SYMBOL = '8';
        }

        enum MDUpdateAction {
            NEW = 0,
            CHANGE = 1,
            DELETE = 2,
            OVERLAY = 5,
        }

        enum MDEntryType {
            BID = '0',
            OFFER = '1',
            TRADE = '2',
            OPENING_PRICE = '4',
            SETTLEMENT_PRICE = '6',
            TRADING_SESSION_HIGH_PRICE = '7',
            TRADING_SESSION_LOW_PRICE = '8',
            TRADE_VOLUME = 'B',
            OPEN_INTEREST = 'C',
            SIMULATED_SELL = 'E',
            SIMULATED_BUY = 'F',
            EMPTY_THE_BOOK = 'J',
            SESSION_HIGH_BID = 'N',
            SESSION_LOW_OFFER = 'O',
            FIXING_PRICE = 'W',
            CASH_NOTE = 'X',
        }

        enum MarketStateIdentifier {
            PRE_OPENING = 0,
            OPENING_MODE = 1,
            CONTINUOUS_TRADING_MODE = 2,
        }

        enum TickDirection {
            PLUS_TICK = 0,
            MINUS_TICK = 1,
        }

        enum OpenCloseSettleFlag {
            THEORETICAL_PRICE_VALUE = 5,
            ACTUAL_PRELIMINARY_NOT_ROUNDED = 100,
            ACTUAL_PRELIMINARY_ROUNDED = 101,
        }

        // SBE enum with fewer than two values: AdHoc rejects such enums, kept as a constants container.
        public struct MDQuoteType {
            public const byte TRADABLE = 1;
        }

        enum MatchEventIndicator {
            MID_EVENT = '0',
            BEGINNING_EVENT = '1',
            END_EVENT = '2',
            BEGINNING_AND_END_EVENT = '3',
        }

        [Flags]
        enum QuoteCondition {
            Implied = 1,
            ExchangeBest = 2,
        }

        [Flags]
        enum TradeCondition {
            OpeningTrade = 1,
            CmeGlobexPrice = 2,
        }

        // ═════════════════════════ topology ═════════════════════════

        // The side that opens the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Initiator : Host { }

        // The side that accepts the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Acceptor : Host { }

        interface Session : Connects<Initiator, Acceptor> {
            // Every SBE message, either direction; composites and typedefs stay sub-packs.
            [_____lr_____<(NewOrder, OrderCancelRequest, OrderCancelReplaceRequest, MarketDataIncrementalRefresh, MarketDataIncrementalRefreshTrades, MassQuote)>]
            struct Established { }
        }

        // ═════════════════════════ SBE metadata attributes ═════════════════════════

        /** SBE field id (the FIX tag number). */
        public class TagAttribute : Attribute { public TagAttribute(int id) { } }

        /** Schema version that introduced the element. */
        public class SinceVersionAttribute : Attribute { public SinceVersionAttribute(int version) { } }

        /** Schema version that deprecated the element. */
        public class DeprecatedAttribute : Attribute { public DeprecatedAttribute(int version) { } }

        /** Wire value that means 'not set' for an optional encoding. */
        public class NullValueAttribute : Attribute { public NullValueAttribute(string value) { } }

        /** Character encoding of a char / var-data encoding. */
        public class CharacterEncodingAttribute : Attribute { public CharacterEncodingAttribute(string encoding) { } }

        /** FIX semantic data type of the encoding (Qty, Price, UTCTimestamp, ...). */
        public class SemanticTypeAttribute : Attribute { public SemanticTypeAttribute(string type) { } }

        /** Composite that frames the repeating group on the wire. */
        public class DimensionTypeAttribute : Attribute { public DimensionTypeAttribute(string composite) { } }

        /** Fixed block length of the message / group root block on the SBE wire. */
        public class BlockLengthAttribute : Attribute { public BlockLengthAttribute(long bytes) { } }

    }
}
