// Generated by FIX2AdHoc (QuickFIX data dictionary) (https://github.com/AdHoc-Protocol)
// Sources: FIXT11.xml
// FIX FIXT 1.1 SP0: 8 messages, 2 components, 71 fields
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.fix {
    /**
        <see cref = 'Heartbeat'/>
        <see cref = 'Logon'/>
        <see cref = 'Logout'/>
        <see cref = 'Reject'/>
        <see cref = 'ResendRequest'/>
        <see cref = 'SequenceReset'/>
        <see cref = 'TestRequest'/>
        <see cref = 'XMLnonFIX'/>
    */
    public interface FIXT11 {

        // Permissive defaults for FIX-sourced data — override per field with [D(+N)] / [D(N)].
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ standard header / trailer ═════════════════════════
        // Plain packs, not HeaderFor<>: FIX header fields are strings and optional, which AdHoc headers do not allow.

        class Header {
            [Tag(8)] string BeginString;
            [Tag(9), A, FixType("LENGTH")] int BodyLength;
            [Tag(35)] string MsgType;
            [Tag(1128)] ApplVerID? ApplVerID;
            [Tag(1156)] int? ApplExtID;
            [Tag(1129)] string CstmApplVerID;
            [Tag(49)] string SenderCompID;
            [Tag(56)] string TargetCompID;
            [Tag(115)] string OnBehalfOfCompID;
            [Tag(128)] string DeliverToCompID;
            [Tag(90), A, FixType("LENGTH")] int? SecureDataLen;
            [Tag(91), FixType("DATA"), D(65535)] Binary[,,] SecureData;
            [Tag(34), A, FixType("SEQNUM")] long MsgSeqNum;
            [Tag(50)] string SenderSubID;
            [Tag(142)] string SenderLocationID;
            [Tag(57)] string TargetSubID;
            [Tag(143)] string TargetLocationID;
            [Tag(116)] string OnBehalfOfSubID;
            [Tag(144)] string OnBehalfOfLocationID;
            [Tag(129)] string DeliverToSubID;
            [Tag(145)] string DeliverToLocationID;
            [Tag(43)] bool? PossDupFlag;
            [Tag(97)] bool? PossResend;
            [Tag(52)] DateTime SendingTime;
            [Tag(122)] DateTime? OrigSendingTime;
            [Tag(212), A, FixType("LENGTH")] int? XmlDataLen;
            [Tag(213), FixType("DATA"), D(65535)] Binary[,,] XmlData;
            [Tag(347)] string MessageEncoding;
            [Tag(369), A, FixType("SEQNUM")] long? LastMsgSeqNumProcessed;
            [Tag(627)] NoHopsGroup[,,] NoHops;
            public class NoHopsGroup {
                [Tag(628)] string HopCompID;
                [Tag(629)] DateTime? HopSendingTime;
                [Tag(630), A, FixType("SEQNUM")] long? HopRefID;
            }
        }

        class Trailer {
            [Tag(93), A, FixType("LENGTH")] int? SignatureLength;
            [Tag(89), FixType("DATA"), D(65535)] Binary[,,] Signature;
            [Tag(10)] string CheckSum;
        }

        // ═════════════════════════ messages ═════════════════════════

        class Heartbeat {
            public const string MSG_TYPE = "0";
            public const string MSG_CAT = "admin";
            Header header;
            [Tag(112)] string TestReqID;
            Trailer trailer;
        }

        class TestRequest {
            public const string MSG_TYPE = "1";
            public const string MSG_CAT = "admin";
            Header header;
            [Tag(112)] string TestReqID;
            Trailer trailer;
        }

        class ResendRequest {
            public const string MSG_TYPE = "2";
            public const string MSG_CAT = "admin";
            Header header;
            [Tag(7), A, FixType("SEQNUM")] long BeginSeqNo;
            [Tag(16), A, FixType("SEQNUM")] long EndSeqNo;
            Trailer trailer;
        }

        class Reject {
            public const string MSG_TYPE = "3";
            public const string MSG_CAT = "admin";
            Header header;
            [Tag(45), A, FixType("SEQNUM")] long RefSeqNum;
            [Tag(371)] int? RefTagID;
            [Tag(372)] string RefMsgType;
            [Tag(1130)] string RefApplVerID;
            [Tag(1406)] int? RefApplExtID;
            [Tag(1131)] string RefCstmApplVerID;
            [Tag(373)] SessionRejectReason? SessionRejectReason;
            [Tag(58)] string Text;
            [Tag(354), A, FixType("LENGTH")] int? EncodedTextLen;
            [Tag(355), FixType("DATA"), D(65535)] Binary[,,] EncodedText;
            Trailer trailer;
        }

        class SequenceReset {
            public const string MSG_TYPE = "4";
            public const string MSG_CAT = "admin";
            Header header;
            [Tag(123)] bool? GapFillFlag;
            [Tag(36), A, FixType("SEQNUM")] long NewSeqNo;
            Trailer trailer;
        }

        class Logout {
            public const string MSG_TYPE = "5";
            public const string MSG_CAT = "admin";
            Header header;
            [Tag(1409)] SessionStatus? SessionStatus;
            [Tag(58)] string Text;
            [Tag(354), A, FixType("LENGTH")] int? EncodedTextLen;
            [Tag(355), FixType("DATA"), D(65535)] Binary[,,] EncodedText;
            Trailer trailer;
        }

        class Logon {
            public const string MSG_TYPE = "A";
            public const string MSG_CAT = "admin";
            Header header;
            [Tag(98)] EncryptMethod EncryptMethod;
            [Tag(108)] int HeartBtInt;
            [Tag(95), A, FixType("LENGTH")] int? RawDataLength;
            [Tag(96), FixType("DATA"), D(65535)] Binary[,,] RawData;
            [Tag(141)] bool? ResetSeqNumFlag;
            [Tag(789), A, FixType("SEQNUM")] long? NextExpectedMsgSeqNum;
            [Tag(383), A, FixType("LENGTH")] int? MaxMessageSize;
            // component MsgTypeGrp has no members in this dictionary
            [Tag(464)] bool? TestMessageIndicator;
            [Tag(553)] string Username;
            [Tag(554)] string Password;
            [Tag(925)] string NewPassword;
            [Tag(1400)] int? EncryptedPasswordMethod;
            [Tag(1401), A, FixType("LENGTH")] int? EncryptedPasswordLen;
            [Tag(1402), FixType("DATA"), D(65535)] Binary[,,] EncryptedPassword;
            [Tag(1403), A, FixType("LENGTH")] int? EncryptedNewPasswordLen;
            [Tag(1404), FixType("DATA"), D(65535)] Binary[,,] EncryptedNewPassword;
            [Tag(1409)] SessionStatus? SessionStatus;
            [Tag(1137)] string DefaultApplVerID;
            [Tag(1407)] int? DefaultApplExtID;
            [Tag(1408)] string DefaultCstmApplVerID;
            [Tag(58)] string Text;
            [Tag(354), A, FixType("LENGTH")] int? EncodedTextLen;
            [Tag(355), FixType("DATA"), D(65535)] Binary[,,] EncodedText;
            Trailer trailer;
        }

        class XMLnonFIX {
            public const string MSG_TYPE = "n";
            public const string MSG_CAT = "admin";
            Header header;
            Trailer trailer;
        }

        // ═════════════════════════ components ═════════════════════════

        class HopGrp {
            [Tag(627)] NoHopsGroup[,,] NoHops;
            public class NoHopsGroup {
                [Tag(628)] string HopCompID;
                [Tag(629)] DateTime? HopSendingTime;
                [Tag(630), A, FixType("SEQNUM")] long? HopRefID;
            }
        }
        // component MsgTypeGrp is declared without members in this dictionary and is not emitted.

        // ═════════════════════════ field value sets ═════════════════════════

        /** Tag 98, FIX type INT. */
        enum EncryptMethod {
            NONE_OTHER = 0,
            PKCS = 1,
            DES = 2,
            PKCSDES = 3,
            PGPDES = 4,
            PGPDESMD5 = 5,
            PEMDESMD5 = 6,
        }

        /** Tag 373, FIX type INT. */
        enum SessionRejectReason {
            INVALID_TAG_NUMBER = 0,
            REQUIRED_TAG_MISSING = 1,
            TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE = 2,
            UNDEFINED_TAG = 3,
            TAG_SPECIFIED_WITHOUT_A_VALUE = 4,
            VALUE_IS_INCORRECT = 5,
            INCORRECT_DATA_FORMAT_FOR_VALUE = 6,
            DECRYPTION_PROBLEM = 7,
            SIGNATURE_PROBLEM = 8,
            COMPID_PROBLEM = 9,
            SENDINGTIME_ACCURACY_PROBLEM = 10,
            INVALID_MSGTYPE = 11,
            XML_VALIDATION_ERROR = 12,
            TAG_APPEARS_MORE_THAN_ONCE = 13,
            TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER = 14,
            REPEATING_GROUP_FIELDS_OUT_OF_ORDER = 15,
            INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP = 16,
            NON_DATA_VALUE_INCLUDES_FIELD_DELIMITER = 17,
            INVALID_UNSUPPORTED_APPLICATION_VERSION = 18,
            OTHER = 99,
        }

        /** Tag 1128, FIX type STRING. */
        enum ApplVerID {
            FIX27 = '0',
            FIX30 = '1',
            FIX40 = '2',
            FIX41 = '3',
            FIX42 = '4',
            FIX43 = '5',
            FIX44 = '6',
            FIX50 = '7',
            FIX50_SP1 = '8',
            FIX50_SP2 = '9',
        }

        /** Tag 1409, FIX type INT. */
        enum SessionStatus {
            SESSION_ACTIVE = 0,
            SESSION_PASSWORD_CHANGED = 1,
            SESSION_PASSWORD_DUE_TO_EXPIRE = 2,
            NEW_SESSION_PASSWORD_DOES_NOT_COMPLY_WITH_POLICY = 3,
            SESSION_LOGOUT_COMPLETE = 4,
            INVALID_USERNAME_OR_PASSWORD = 5,
            ACCOUNT_LOCKED = 6,
            LOGONS_ARE_NOT_ALLOWED_AT_THIS_TIME = 7,
            PASSWORD_EXPIRED = 8,
        }

        // ═════════════════════════ topology ═════════════════════════

        // The side that sends Logon.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Initiator : Host { }

        // The side that accepts the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Acceptor : Host { }

        interface Session : Connects<Initiator, Acceptor> {
            // Every FIX message (admin and application), either direction; components and groups stay sub-packs.
            [_____lr_____<(Heartbeat, TestRequest, ResendRequest, Reject, SequenceReset, Logout, Logon, XMLnonFIX)>]
            struct Established { }
        }

        // ═════════════════════════ FIX metadata attributes ═════════════════════════

        /** FIX tag number of the field. */
        public class TagAttribute : Attribute { public TagAttribute(int tag) { } }

        /** FIX data type of the field where the C# type is an approximation. */
        public class FixTypeAttribute : Attribute { public FixTypeAttribute(string type) { } }

        /** Name of the constants container holding the field's enumerated values. */
        public class ValuesAttribute : Attribute { public ValuesAttribute(string container) { } }

    }
}
