// Generated by FIX2AdHoc (SBE message schema) (https://github.com/AdHoc-Protocol)
// Sources: group-with-data-schema.xml
// SBE package: group.with.data, schema id: 1, version: 0, semanticVersion: 5.2, byteOrder: littleEndian
// Schema description: 
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.fix {
    /**
        <see cref = 'TestMessage1'/>
        <see cref = 'TestMessage2'/>
        <see cref = 'TestMessage3'/>
        <see cref = 'TestMessage4'/>
    */
    public interface group_with_data_schema {

        // Permissive defaults for FIX-sourced data — override per field with [D(+N)] / [D(N)].
        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        // ═════════════════════════ messages ═════════════════════════

        /**
        Group with single var data
        */
        [BlockLength(16)] class TestMessage1 {
            public const int template_id = 1; // SBE message id
            [Tag(1), SemanticType("int")] uint Tag1;
            [Tag(2), DimensionType("groupSizeEncoding"), D(255)] EntriesGroup[,,] Entries;
            public class EntriesGroup {
                [Tag(3)] Symbol TagGroup1;
                [Tag(4), SemanticType("int")] long TagGroup2;
                [Tag(5), D(+255), CharacterEncoding("UTF-8")] string varDataField;
            }
        }

        /**
        Group with multiple var data
        */
        [BlockLength(16)] class TestMessage2 {
            public const int template_id = 2; // SBE message id
            [Tag(1), SemanticType("int")] uint Tag1;
            [Tag(2), DimensionType("groupSizeEncoding"), D(255)] EntriesGroup[,,] Entries;
            public class EntriesGroup {
                [Tag(3)] Symbol TagGroup1;
                [Tag(4), SemanticType("int")] long TagGroup2;
                [Tag(5), D(+255), CharacterEncoding("UTF-8")] string varDataField1;
                [Tag(6), D(+255), CharacterEncoding("UTF-8")] string varDataField2;
            }
        }

        /**
        Nested group with var data
        */
        [BlockLength(16)] class TestMessage3 {
            public const int template_id = 3; // SBE message id
            [Tag(1), SemanticType("int")] uint Tag1;
            [Tag(2), DimensionType("groupSizeEncoding"), D(255)] EntriesGroup[,,] Entries;
            public class EntriesGroup {
                [Tag(3)] Symbol TagGroup1;
                [Tag(4), DimensionType("groupSizeEncoding"), D(255)] NestedEntriesGroup[,,] NestedEntries;
                public class NestedEntriesGroup {
                    [Tag(5), SemanticType("int")] long TagGroup2;
                    [Tag(6), D(+255), CharacterEncoding("UTF-8")] string varDataFieldNested;
                }
                [Tag(7), D(+255), CharacterEncoding("UTF-8")] string varDataField;
            }
        }

        /**
        Group with only multiple var data
        */
        [BlockLength(16)] class TestMessage4 {
            public const int template_id = 4; // SBE message id
            [Tag(1), SemanticType("int")] uint Tag1;
            [Tag(2), DimensionType("groupSizeEncoding"), D(255)] EntriesGroup[,,] Entries;
            public class EntriesGroup {
                [Tag(5), D(+255), CharacterEncoding("UTF-8")] string varDataField1;
                [Tag(6), D(+255), CharacterEncoding("UTF-8")] string varDataField2;
            }
        }

        // ═════════════════════════ types (typedefs, enums, sets, composites) ═════════════════════════

        /**
        Symbol
        */
        class Symbol { [D(+9), SemanticType("char")] string TYPEDEF; }

        /**
        Message identifiers and length of message root
        */
        class messageHeader {
            ushort blockLength;
            ushort templateId;
            ushort schemaId;
            ushort version;
        }

        /**
        Repeating group dimensions
        */
        class groupSizeEncoding {
            ushort blockLength;
            [SemanticType("NumInGroup")] byte numInGroup;
        }

        [SemanticType("Length")] class varDataEncoding {
            [SemanticType("Length")] byte length;
            [CharacterEncoding("UTF-8"), SemanticType("data")] char varData;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The side that opens the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Initiator : Host { }

        // The side that accepts the session.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Acceptor : Host { }

        interface Session : Connects<Initiator, Acceptor> {
            // Every SBE message, either direction; composites and typedefs stay sub-packs.
            [_____lr_____<(TestMessage1, TestMessage2, TestMessage3, TestMessage4)>]
            struct Established { }
        }

        // ═════════════════════════ SBE metadata attributes ═════════════════════════

        /** SBE field id (the FIX tag number). */
        public class TagAttribute : Attribute { public TagAttribute(int id) { } }

        /** Schema version that introduced the element. */
        public class SinceVersionAttribute : Attribute { public SinceVersionAttribute(int version) { } }

        /** Schema version that deprecated the element. */
        public class DeprecatedAttribute : Attribute { public DeprecatedAttribute(int version) { } }

        /** Wire value that means 'not set' for an optional encoding. */
        public class NullValueAttribute : Attribute { public NullValueAttribute(string value) { } }

        /** Character encoding of a char / var-data encoding. */
        public class CharacterEncodingAttribute : Attribute { public CharacterEncodingAttribute(string encoding) { } }

        /** FIX semantic data type of the encoding (Qty, Price, UTCTimestamp, ...). */
        public class SemanticTypeAttribute : Attribute { public SemanticTypeAttribute(string type) { } }

        /** Composite that frames the repeating group on the wire. */
        public class DimensionTypeAttribute : Attribute { public DimensionTypeAttribute(string composite) { } }

        /** Fixed block length of the message / group root block on the SBE wire. */
        public class BlockLengthAttribute : Attribute { public BlockLengthAttribute(long bytes) { } }

    }
}
